# Generated by Django 4.2.15 on 2024-08-23 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('full_name', models.CharField(max_length=50, verbose_name='Ф.И.О.')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='LastDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_last_dispatch', models.DateField(blank=True, null=True, verbose_name='Дата последней попытки')),
                ('status', models.BooleanField(default=True, verbose_name='Статус отправки')),
                ('mail_server_response', models.TextField(blank=True, null=True, verbose_name='Ответ почтнового сервера')),
            ],
            options={
                'verbose_name': 'Последняя рассылка',
                'verbose_name_plural': 'Последние рассылки',
            },
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_mail', models.CharField(max_length=100, verbose_name='Тема письма')),
                ('text_mail', models.TextField(verbose_name='Текст письма')),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_dispatch', models.DateField(blank=True, null=True, verbose_name='Дата первой отправки')),
                ('periodicity', models.IntegerField(verbose_name='Периодичность')),
                ('status', models.CharField(max_length=15, verbose_name='Статус')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.client', verbose_name='Клиент')),
                ('last_dispatch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.lastdispatch', verbose_name='Последняя рассылка')),
                ('mail', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.mail', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
    ]
