# Generated by Django 4.2.15 on 2024-08-24 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='mail',
        ),
        migrations.AddField(
            model_name='mail',
            name='mailing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='lastdispatch',
            name='date_last_dispatch',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последней отправки'),
        ),
    ]
