# Generated by Django 4.2.15 on 2024-08-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_remove_mailing_mail_mail_mailing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='number_clients',
            field=models.IntegerField(default=0, verbose_name='Колличество клиентов'),
        ),
    ]
