# Generated by Django 4.2.15 on 2024-08-27 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_mailing_number_clients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='last_dispatch',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='number_clients',
        ),
        migrations.AddField(
            model_name='lastdispatch',
            name='mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', verbose_name='Рассылка'),
        ),
    ]
