# Generated by Django 4.2.15 on 2024-08-27 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_remove_mailing_last_dispatch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='mailing',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', verbose_name='Рассылка'),
            preserve_default=False,
        ),
    ]
