# Generated by Django 4.2.15 on 2024-08-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_alter_mail_mailing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='first_dispatch',
            field=models.DateField(default=None, verbose_name='Дата первой отправки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mailing',
            name='last_mailing',
            field=models.DateField(default=None, verbose_name='Дата последней отправки'),
            preserve_default=False,
        ),
    ]
