# Generated by Django 4.2.15 on 2024-09-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_block',
            field=models.BooleanField(default=False, verbose_name='Заблокирован'),
        ),
    ]
